slimpay:
  app_id: 'vaincrelautisme01'
  app_secret: '8pgWCFFqomyeQdHhmJRALIwujEekvH8UBsaZnw0X'
  encoded_key: 'dmFpbmNyZWxhdXRpc21lMDE6OHBnV0NGRnFvbXllUWRIaG1KUkFMSXd1akVla3ZIOFVCc2FabncwWA=='
  creditor_reference: 'vaincrelautisme'
  server: 'https://api-sandbox.slimpay.net'
  url:
    create_order: 'https://api-sandbox.slimpay.net/orders'