slimpay:
  app_id: 'vaincrelautisme01'
  app_secret: 'Dm29jZbhQjGrdMNeY6ifyayU6qqBggSWTIEO8G8N'
  encoded_key: 'dmFpbmNyZWxhdXRpc21lMDE6RG0yOWpaYmhRakdyZE1OZVk2aWZ5YXlVNnFxQmdnU1dUSUVPOEc4Tg=='
  creditor_reference: 'vaincrelautisme'
  server: 'https://api-sandbox.slimpay.net'
  url:
    create_order: '/orders'
paypal:
  server: 'https://api.sandbox.paypal.com/v1'
  url: 
    get_token: /oauth2/token
  callback_url_failure: https://vaincre-l-autisme.herokuapp.com/anulation
  callback_url_success: https://vaincre-l-autisme.herokuapp.com/validation
    key: 'QVIyZzROSVBzZHpRUi1pZDUxS19hVWdsbnI5bHZDcDludHU0b1VNMTA5eHVDTUVzNTktNklKd3ZXVEtiQm9Qa3VkTE4zTGFLRnpQLWJBMFE6RUF2RXA5OUhUWmlXMzhsMGFIRFRyUmNMSURTQVp3X2VZdlRVU25seXRUYkhHU214SVVvUEl6eU5qUkJhNmVVMFZORWRQUWpvM0hOQ0I4cVY'
encrypt:
  key: 'EncryptDecryptGurudathBN'
  algorithme: 'AES-128-ECB'